version: '3.9'
services:

    tab:
      image: kjanossy/tab:latest
      ports:
        - 5000:5000
      environment:
        FLASK_DATABASE_URI: postgresql://localhost/tab?user=postgres&password=megyenahegyenaturista
      logging:
        driver: "local"

    watchtower:
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
