version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CURRENT_ENV=${CURRENT_ENV}

    command: python /app/tag_a_bird_backend/app.py  run
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    env_file:
      - ./tag_a_bird_backend/.env
    depends_on:
      - db
    restart: always
    links:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    links:
      - db

volumes:
  postgres_data:
