services:
  app:
    image: ghcr.io/tag-a-bird/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app # Mount the current directory to /app in the container
    platform: linux/amd64 # Specify the platform

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    platform: linux/amd64 # Specify the platform

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    platform: linux/amd64 # Specify the platform

volumes:
  postgres_data:
