version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/tag_a_bird_backend
    command: gunicorn --bind 0.0.0.0:8000 tag_a_bird_backend.app:app
    platform: linux/amd64
    environment:
      - FLASK_CONFIG_TYPE=${FLASK_CONFIG_TYPE}
      - FLASK_APP=${FLASK_APP}
      - FLASK_DATABASE_URI=${FLASK_DATABASE_URI}
      - FLASK_SQLALCHEMY_TRACK_MODIFICATIONS=${FLASK_SQLALCHEMY_TRACK_MODIFICATIONS}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_TESTING=${FLASK_TESTING}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - COREO_API_KEY=${COREO_API_KEY}
      - ADMIN_CREDENTIALS_EMAIL=${ADMIN_CREDENTIALS_EMAIL}
      - ADMIN_CREDENTIALS_PW=${ADMIN_CREDENTIALS_PW}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    platform: linux/amd64

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    platform: linux/amd64

volumes:
  postgres_data:
