version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - nginx
    environment:
      - FLASK_APP
      - FLASK_DATABASE_URI
      - FLASK_SQLALCHEMY_TRACK_MODIFICATIONS
      - FLASK_DEBUG
      - FLASK_SECRET_KEY
      - FLASK_TESTING
      - COREO_API_KEY
      - ADMIN_CREDENTIALS_EMAIL
      - ADMIN_CREDENTIALS_PW

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
