"""auto-generated migration

Revision ID: 0ad55934096b
Revises: e304e8a0b597
Create Date: 2022-11-11 13:26:54.024012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad55934096b'
down_revision = 'e304e8a0b597'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
