"""Initial migration

Revision ID: 201aa151b0a2
Revises: 
Create Date: 2024-07-24 10:19:57.165004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201aa151b0a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'query_config', ['parameter'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query_config', type_='unique')
    # ### end Alembic commands ###
