"""empty message

Revision ID: 6ef2e5fb5e2f
Revises: 550f6986c6da
Create Date: 2022-11-11 13:04:22.331535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef2e5fb5e2f'
down_revision = '550f6986c6da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'comment')
    # ### end Alembic commands ###
