"""auto-generated migration

Revision ID: 8ae39da4a0bb
Revises: 0ad55934096b
Create Date: 2022-11-11 13:27:33.419005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae39da4a0bb'
down_revision = '0ad55934096b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'created_at')
    # ### end Alembic commands ###
