"""empty message

Revision ID: 9f48dca20a71
Revises: 6ef2e5fb5e2f
Create Date: 2022-11-11 13:08:59.036202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f48dca20a71'
down_revision = '6ef2e5fb5e2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'created_at')
    # ### end Alembic commands ###
