name: Build and Deploy

on:
  push:
    branches:
      - can-backend-24

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Create .env file from secrets
        run: |
          echo "FLASK_CONFIG_TYPE=production" >> .env
          echo "FLASK_APP=${{ secrets.FLASK_APP }}" >> .env
          echo "FLASK_DATABASE_URI=${{ secrets.FLASK_DATABASE_URI }}" >> .env
          echo "FLASK_SQLALCHEMY_TRACK_MODIFICATIONS=${{ secrets.FLASK_SQLALCHEMY_TRACK_MODIFICATIONS }}" >> .env
          echo "FLASK_DEBUG=${{ secrets.FLASK_DEBUG }}" >> .env
          echo "FLASK_TESTING=${{ secrets.FLASK_TESTING }}" >> .env
          echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> .env
          echo "COREO_API_KEY=${{ secrets.COREO_API_KEY }}" >> .env
          echo "ADMIN_CREDENTIALS_EMAIL=${{ secrets.ADMIN_CREDENTIALS_EMAIL }}" >> .env
          echo "ADMIN_CREDENTIALS_PW=${{ secrets.ADMIN_CREDENTIALS_PW }}" >> .env

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and deploy
        run: |
          docker-compose down
          docker-compose up -d --build
