name: Backend build
'on':
  pull_request: 
    types:
      closed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: >-
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{
          secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Docker image
        run: >-
          docker build --output
          "type=image,push=true" --tag
          kjanossy/tab ./tag_a_bird_backend/.
