name: build

on:
  workflow_dispatch:
  push:
    branches:
      - can-backend-24

jobs:
  buildimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry install
        working-directory: .

      - name: Build .whl package
        run: poetry build
        working-directory: .

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        run: >
          docker build --output
          "type=image,push=true" --tag
          ghcr.io/tag-a-bird/backend:$GITHUB_REF_SLUG-$GITHUB_RUN_NUMBER  --tag
          ghcr.io/tag-a-bird/backend:$GITHUB_REF_SLUG-latest .
        working-directory: .
